Counter App
Pratiyushkumar/Interview-preparation pull request #1
Opened 2023-09-18 13:41 UTC by Pratiyushkumar

2023-09-19 06:15 UTC, TanishqSingla requested changes

2023-09-19 06:15 UTC, TanishqSingla commented on script.js
> +counterApp();
scripts run automatically so you don't need a function wrapper to initialize your app, if you still want to be redundant to add strict behavior, you can use the HTML `onload` event.

2023-09-19 06:15 UTC, TanishqSingla commented on script.js
> +  decrement.addEventListener('click', () => {
you don't need an arrow function, you can just pass the callback, since you're not handling any arguments. This removes necessary steps. And when vanilla js is concerned getting that file size down really helps

2023-09-19 06:15 UTC, TanishqSingla commented on script.js
> +  increment.addEventListener('click', () => {
same as above

2023-09-19 06:15 UTC, TanishqSingla commented on style.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap');
Always import your fonts in HTML, this way your css file will load faster, and since css is most of the time included in the header importing fonts in HTML would allow your HTML to load faster instead of creating a blocking event (downloading css in this case)

2023-09-19 13:02 UTC, Pratiyushkumar commented on script.js
> +  decrement.addEventListener('click', () => {
done

2023-09-19 13:02 UTC, Pratiyushkumar commented on script.js
> +  increment.addEventListener('click', () => {
done

2023-09-20 09:42 UTC, TanishqSingla approved these changes

2023-09-20 09:58 UTC, merged